---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: xaethos/android-build
    tag: no-sdk
inputs:
 - name: android-sdk-linux
 - name: project-source
outputs:
 - name: build-output
run:
  path: sh
  args:
  - -exc
  - |
    export TERM=${TERM:-dumb}
    # accept all Android-related licenses
    export ANDROID_HOME="$PWD/android-sdk-linux"
    mkdir "$ANDROID_HOME/licenses"
    echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    # inovke gradle build
    cd project-source
    # TODO: is this necessary?
    chmod 777 gradlew
    ./gradlew build
    # copy the .apk artifact to shared output so it can be pushed to hockey app in next step
    cp app/build/outputs/apk/app-debug.apk ../build-output/app.apk