---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: xaethos/android-build
    tag: no-sdk
inputs:
 - name: android-sdk-linux
 - name: project-source
outputs:
 - name: build-output
run:
  path: sh
  args:
  - -exc
  - |
    export TERM=${TERM:-dumb}
    export ANDROID_HOME="$PWD/android-sdk-linux"
    mkdir "$ANDROID_HOME/licenses"
    echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    pwd
    ls
    cd project-source
    chmod 777 gradlew
    mkdir ../../put
    ls ../..
    ./gradlew build
    pwd
    ls
    cp app/build/outputs/apk/app-debug.apk build-output/app.apk
    # cp app/build/outputs/apk/app-debug.apk ../../put/app.apk
    #cd "$PWD"
    #cd ../put
    #cp project-source/app/build/outputs/apk/app-debug.apk app.apk
    #ls