---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: xaethos/android-build
    tag: no-sdk
inputs:
 - name: android-sdk-linux
 - name: project-source
run:
  path: sh
  args:
    - -euxc
    - >-
    TERM=screen-256color
    ANDROID_HOME="$PWD/android-sdk-linux"
    project-source/gradlew --project-dir=project-source :app:build