---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: krzu/android-build
    tag: no-sdk
inputs:
 - name: android-sdk-linux
 - name: project-source
run:
  path: sh
  args:
  - -exc
  - |
    export TERM=${TERM:-dumb}
    export ANDROID_HOME="$PWD/android-sdk-linux"
    mkdir "$ANDROID_HOME/licenses"
    echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    cd project-source
    chmod 777 gradlew
    ./gradlew build