git-uri: https://github.com/krzu/pipeline-test.git
git-branch: master
android-components:
  - android-25
  - build-tools-25.0.3
  - extra-android-m2repository
hockey-app-api-key: 67bd033133404e37b336bd6bbb8b9b1f
hockey-app-token: b8d1ffde9f9e4a18923b02dd5a8560ab