---
resource_types:
  - name: android-sdk
    type: docker-image
    source: {repository: xaethos/android-sdk-resource}
  - name: hockey
    type: docker-image
    source:
      repository: seadowg/hockey-resource
      tag: 0.1.0

resources:
  - name: android-sdk-linux
    type: android-sdk
    source:
      components: ((android-components))
  - name: project-source
    type: git
    source:
      uri: ((git-uri))
      branch: ((git-branch))
  - name: hockey
    type: hockey
    source:
      app_id: ((hockey-app-api-key))
      token: ((hockey-app-token))
 
jobs:
  - name: build-and-deploy
    public: true
    plan:
      - aggregate:
        - get: android-sdk-linux
        - get: project-source
      - task: build
        file: project-source/ci/build.yml
      - put: hockey
        params:
          path: build-output/app.apk
          downloadable: true